### 14. Lambda functions in Python

##### What is Lambda functions?
A Lmabda function is small, anonymous function[without their name or nameless] written in one single line.


📌 Simple Definition

> A lambda function is one-line function without a name.

### Why Lambda function are used?

* ꪜShort & Clean Code
* ꪜUsed for temporary operations
* ꪜCommon with map(), filter(), reduce(), apply(),sort()
* ꪜImproves readablity in simple logic

### Normal Functions VS Lambda functions


#### Normal Functions

In [2]:
## user-defined function
def square(x):
    return x*x

square(10)

100

In [3]:
square(100)

10000

##### Lambda Functions: Nameless

In [4]:
(lambda x:x*x)(10)

100

In [5]:
(lambda y:y*y)(100)

10000

Notes:

* ꪜSame Output
* ꪜLess Code

#### Syntax of Lambda functions
`(lambda argument:expression)`

##### 📌 Rules:

* ꪜCan have multiple arguments
* ꪜOnly one expression
* ꪜAutmatically returned value
* ꪜNo return keyword

#### Basic Examples:

1. Add Two Numbers:

In [6]:
# Normal Functions 

def sumTwo(a,b):
    sumValue = a+b
    return sumValue

sumTwo(10,20)

30

In [9]:
### anonymous function or lambda function
(lambda a,b : a+b)(10,20)

30

### 2. Square of a Number

In [10]:
# Normal Function 

def sqrNum(num):
    return num**2
sqrNum(10)

100

In [11]:
# lambda function 

(lambda a:a**2)(10)

100

### 3. Check Even or Odd(Condition)

In [12]:
def checkEven(a):
    if a%2==0:
        return f"Even Number: {a}"
checkEven(10)

'Even Number: 10'

In [18]:
### Lambda function

(lambda x:x%2==0 and "Even")(10)

'Even'

In [19]:
### Lambda function

(lambda x:x%2==0 and "Even")(11)

False

In [21]:
def checkEven(a):
    if a%2==0:
        return f"Even Number: {a}"
    else:
        return f"Odd Number: {a}"
checkEven(11)

'Odd Number: 11'

In [22]:
(lambda x:"Even" if x%2==0 else "Odd")(10)

'Even'

In [23]:
(lambda x:"Even" if x%2==0 else "Odd")(11)

'Odd'

### Lambda with Multiple Arguments

In [24]:
def maxThree(a,b,c):
    if a>b and a>c:
        print(a, "is greater")
    elif b>a and b>c:
        print(b, "is greate")
    else:
        print(c,"is greater")
maxThree(11,10,12)

12 is greater

In [30]:
(lambda a,b,c:print(f"{a} is greater") if a>b and a>c else (print(f"{b} is greater") if b>a and b>c else print(f"{c} is greater")))(10,12,13)

13 is greater

Lambda special Functions:

> Filter()  -> condition

> map() --> expression execute

> reduce() -> single result

> sort() --> sorting

> apply() --> apply

Lambda with Filter()

prupose:
Filter elements based on conditons

In [32]:
numbers = [10,11,12,15,14,16,18,17,19,20,22,24,26,23,25,2,72,82,88,89]


def evenNum():
    for i in numbers:
        if i%2==0:
            print(i,"Even")
        else:
            print(i,"Odd")
evenNum()

10 Even
11 Odd
12 Even
15 Odd
14 Even
16 Even
18 Even
17 Odd
19 Odd
20 Even
22 Even
24 Even
26 Even
23 Odd
25 Odd
2 Even
72 Even
82 Even
88 Even
89 Odd

### Lambda functions

syntax:
filter(func, sequence)

In [33]:
num = [10,11,12,15,14]

def evenNum(x):
    if x%2==0:
        return "Even"

In [35]:
list(filter(evenNum,num))

[10, 12, 14]

In [36]:
tuple(filter(evenNum,num))

(10, 12, 14)

### lambda with filter

In [38]:
list(filter(lambda a:a%2==0,num))

[10, 12, 14]

#### Lambda with Map

Purpose:

Apply a function to each element in the list.


syntax:

`map(function,sequence)`

In [40]:
num = [10,11,12,15,14]

def sqrNum():
    for i in num:
        print(i,":",i*i)
sqrNum()

10 : 100
11 : 121
12 : 144
15 : 225
14 : 196

In [41]:
def sqrNum(x):
    return x*x
sqrNum(10)

100

In [43]:
num = [10,11,12,15,14]
list(map(sqrNum,num))

[100, 121, 144, 225, 196]

In [45]:
### with Lambda function
num = [10,11,12,15,14]
list(map(lambda i: i * i,num))

[100, 121, 144, 225, 196]

### lambda with reduce()

📌 required functools library

syntax:

reduce(function, sequence)

In [47]:
from functools import reduce

In [49]:
num = [10,11,12,15,14]  # add, sub, multiple, divide

reduce(lambda a,b:a+b,num)

62

In [50]:
num = [10,11,12,15,14]  # add, sub, multiple, divide

reduce(lambda a,b:a-b,num)

-42

In [55]:
def redNum(a,b):
    return a+b

In [56]:
num = [10,11,12,15,14] 
reduce(redNum,num)

62

In [57]:
#lambda
num = [10,11,12,15,14] 
reduce(lambda a,b:a+b,num)

62

### Lambda with Sort()

syntax:

`sorted(sequence, function)`

In [61]:
students = [("Ramesh",66,65),("Anita",92,17),("Ankita",55,108)]
print(students)

[('Ramesh', 66, 65), ('Anita', 92, 17), ('Ankita', 55, 108)]

In [64]:
sorted(students, key = lambda x:x[2])

[('Anita', 92, 17), ('Ramesh', 66, 65), ('Ankita', 55, 108)]

### Lambda with apply()

In [65]:
data  = [1,2,3,4,5,6,7,8,9,10]

# dataframe = row+column

In [66]:
data  = [1,2,3,4,5,6,7,8,9,10]  # one direction

In [67]:
import pandas as pd

In [69]:
df = pd.DataFrame(data)
df

    0
0   1
1   2
2   3
3   4
4   5
5   6
6   7
7   8
8   9
9  10

In [70]:
data = [[10,12,13],[40,50,60]]
print(data)

[[10, 12, 13], [40, 50, 60]]

In [72]:
df2 = pd.DataFrame(data)
df2

    0   1   2
0  10  12  13
1  40  50  60

In [73]:
## find the square of the dataframe

In [74]:
df3 = df2.apply(lambda a:a**2)
df3

      0     1     2
0   100   144   169
1  1600  2500  3600